<?php
/**
 * DocumentStatusEnum
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PandaDoc Public API
 *
 * PandaDoc Public API documentation
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PandaDoc\Client\Model;
use \PandaDoc\Client\ObjectSerializer;

/**
 * DocumentStatusEnum Class Doc Comment
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentStatusEnum
{
    /**
     * Possible values of this enum
     */
    const DRAFT = 'document.draft';

    const SENT = 'document.sent';

    const COMPLETED = 'document.completed';

    const UPLOADED = 'document.uploaded';

    const ERROR = 'document.error';

    const VIEWED = 'document.viewed';

    const WAITING_APPROVAL = 'document.waiting_approval';

    const APPROVED = 'document.approved';

    const REJECTED = 'document.rejected';

    const WAITING_PAY = 'document.waiting_pay';

    const PAID = 'document.paid';

    const VOIDED = 'document.voided';

    const DECLINED = 'document.declined';

    const EXTERNAL_REVIEW = 'document.external_review';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DRAFT,
            self::SENT,
            self::COMPLETED,
            self::UPLOADED,
            self::ERROR,
            self::VIEWED,
            self::WAITING_APPROVAL,
            self::APPROVED,
            self::REJECTED,
            self::WAITING_PAY,
            self::PAID,
            self::VOIDED,
            self::DECLINED,
            self::EXTERNAL_REVIEW
        ];
    }
}


