<?php
/**
 * DocumentDetailsResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PandaDoc Public API
 *
 * PandaDoc Public API documentation
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PandaDoc\Client\Model;

use \ArrayAccess;
use \PandaDoc\Client\ObjectSerializer;

/**
 * DocumentDetailsResponse Class Doc Comment
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class DocumentDetailsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DocumentDetailsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'autonumberingSequenceNamePrefix' => 'mixed',
        'dateCreated' => 'string',
        'dateModified' => 'string',
        'dateCompleted' => 'string',
        'createdBy' => '\PandaDoc\Client\Model\DocumentDetailsResponseCreatedBy',
        'template' => '\PandaDoc\Client\Model\DocumentDetailsResponseTemplate',
        'expirationDate' => 'mixed',
        'metadata' => 'object',
        'tokens' => 'object[]',
        'fields' => 'object[]',
        'pricing' => '\PandaDoc\Client\Model\PricingTablesResponse',
        'version' => 'string',
        'tags' => 'string[]',
        'sentBy' => 'mixed',
        'recipients' => '\PandaDoc\Client\Model\DocumentDetailsResponseRecipients[]',
        'grandTotal' => '\PandaDoc\Client\Model\DocumentDetailsResponseGrandTotal',
        'linkedObjects' => '\PandaDoc\Client\Model\DocumentDetailsResponseLinkedObjects[]',
        'status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'autonumberingSequenceNamePrefix' => null,
        'dateCreated' => null,
        'dateModified' => null,
        'dateCompleted' => null,
        'createdBy' => null,
        'template' => null,
        'expirationDate' => null,
        'metadata' => null,
        'tokens' => null,
        'fields' => null,
        'pricing' => null,
        'version' => null,
        'tags' => null,
        'sentBy' => null,
        'recipients' => null,
        'grandTotal' => null,
        'linkedObjects' => null,
        'status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'autonumberingSequenceNamePrefix' => 'autonumbering_sequence_name_prefix',
        'dateCreated' => 'date_created',
        'dateModified' => 'date_modified',
        'dateCompleted' => 'date_completed',
        'createdBy' => 'created_by',
        'template' => 'template',
        'expirationDate' => 'expiration_date',
        'metadata' => 'metadata',
        'tokens' => 'tokens',
        'fields' => 'fields',
        'pricing' => 'pricing',
        'version' => 'version',
        'tags' => 'tags',
        'sentBy' => 'sent_by',
        'recipients' => 'recipients',
        'grandTotal' => 'grand_total',
        'linkedObjects' => 'linked_objects',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'autonumberingSequenceNamePrefix' => 'setAutonumberingSequenceNamePrefix',
        'dateCreated' => 'setDateCreated',
        'dateModified' => 'setDateModified',
        'dateCompleted' => 'setDateCompleted',
        'createdBy' => 'setCreatedBy',
        'template' => 'setTemplate',
        'expirationDate' => 'setExpirationDate',
        'metadata' => 'setMetadata',
        'tokens' => 'setTokens',
        'fields' => 'setFields',
        'pricing' => 'setPricing',
        'version' => 'setVersion',
        'tags' => 'setTags',
        'sentBy' => 'setSentBy',
        'recipients' => 'setRecipients',
        'grandTotal' => 'setGrandTotal',
        'linkedObjects' => 'setLinkedObjects',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'autonumberingSequenceNamePrefix' => 'getAutonumberingSequenceNamePrefix',
        'dateCreated' => 'getDateCreated',
        'dateModified' => 'getDateModified',
        'dateCompleted' => 'getDateCompleted',
        'createdBy' => 'getCreatedBy',
        'template' => 'getTemplate',
        'expirationDate' => 'getExpirationDate',
        'metadata' => 'getMetadata',
        'tokens' => 'getTokens',
        'fields' => 'getFields',
        'pricing' => 'getPricing',
        'version' => 'getVersion',
        'tags' => 'getTags',
        'sentBy' => 'getSentBy',
        'recipients' => 'getRecipients',
        'grandTotal' => 'getGrandTotal',
        'linkedObjects' => 'getLinkedObjects',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['autonumberingSequenceNamePrefix'] = $data['autonumberingSequenceNamePrefix'] ?? null;
        $this->container['dateCreated'] = $data['dateCreated'] ?? null;
        $this->container['dateModified'] = $data['dateModified'] ?? null;
        $this->container['dateCompleted'] = $data['dateCompleted'] ?? null;
        $this->container['createdBy'] = $data['createdBy'] ?? null;
        $this->container['template'] = $data['template'] ?? null;
        $this->container['expirationDate'] = $data['expirationDate'] ?? null;
        $this->container['metadata'] = $data['metadata'] ?? null;
        $this->container['tokens'] = $data['tokens'] ?? null;
        $this->container['fields'] = $data['fields'] ?? null;
        $this->container['pricing'] = $data['pricing'] ?? null;
        $this->container['version'] = $data['version'] ?? null;
        $this->container['tags'] = $data['tags'] ?? null;
        $this->container['sentBy'] = $data['sentBy'] ?? null;
        $this->container['recipients'] = $data['recipients'] ?? null;
        $this->container['grandTotal'] = $data['grandTotal'] ?? null;
        $this->container['linkedObjects'] = $data['linkedObjects'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets autonumberingSequenceNamePrefix
     *
     * @return mixed|null
     */
    public function getAutonumberingSequenceNamePrefix()
    {
        return $this->container['autonumberingSequenceNamePrefix'];
    }

    /**
     * Sets autonumberingSequenceNamePrefix
     *
     * @param mixed|null $autonumberingSequenceNamePrefix autonumberingSequenceNamePrefix
     *
     * @return self
     */
    public function setAutonumberingSequenceNamePrefix($autonumberingSequenceNamePrefix)
    {
        $this->container['autonumberingSequenceNamePrefix'] = $autonumberingSequenceNamePrefix;

        return $this;
    }

    /**
     * Gets dateCreated
     *
     * @return string|null
     */
    public function getDateCreated()
    {
        return $this->container['dateCreated'];
    }

    /**
     * Sets dateCreated
     *
     * @param string|null $dateCreated dateCreated
     *
     * @return self
     */
    public function setDateCreated($dateCreated)
    {
        $this->container['dateCreated'] = $dateCreated;

        return $this;
    }

    /**
     * Gets dateModified
     *
     * @return string|null
     */
    public function getDateModified()
    {
        return $this->container['dateModified'];
    }

    /**
     * Sets dateModified
     *
     * @param string|null $dateModified dateModified
     *
     * @return self
     */
    public function setDateModified($dateModified)
    {
        $this->container['dateModified'] = $dateModified;

        return $this;
    }

    /**
     * Gets dateCompleted
     *
     * @return string|null
     */
    public function getDateCompleted()
    {
        return $this->container['dateCompleted'];
    }

    /**
     * Sets dateCompleted
     *
     * @param string|null $dateCompleted dateCompleted
     *
     * @return self
     */
    public function setDateCompleted($dateCompleted)
    {
        $this->container['dateCompleted'] = $dateCompleted;

        return $this;
    }

    /**
     * Gets createdBy
     *
     * @return \PandaDoc\Client\Model\DocumentDetailsResponseCreatedBy|null
     */
    public function getCreatedBy()
    {
        return $this->container['createdBy'];
    }

    /**
     * Sets createdBy
     *
     * @param \PandaDoc\Client\Model\DocumentDetailsResponseCreatedBy|null $createdBy createdBy
     *
     * @return self
     */
    public function setCreatedBy($createdBy)
    {
        $this->container['createdBy'] = $createdBy;

        return $this;
    }

    /**
     * Gets template
     *
     * @return \PandaDoc\Client\Model\DocumentDetailsResponseTemplate|null
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param \PandaDoc\Client\Model\DocumentDetailsResponseTemplate|null $template template
     *
     * @return self
     */
    public function setTemplate($template)
    {
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets expirationDate
     *
     * @return mixed|null
     */
    public function getExpirationDate()
    {
        return $this->container['expirationDate'];
    }

    /**
     * Sets expirationDate
     *
     * @param mixed|null $expirationDate expirationDate
     *
     * @return self
     */
    public function setExpirationDate($expirationDate)
    {
        $this->container['expirationDate'] = $expirationDate;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return object|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param object|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets tokens
     *
     * @return object[]|null
     */
    public function getTokens()
    {
        return $this->container['tokens'];
    }

    /**
     * Sets tokens
     *
     * @param object[]|null $tokens tokens
     *
     * @return self
     */
    public function setTokens($tokens)
    {
        $this->container['tokens'] = $tokens;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return object[]|null
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param object[]|null $fields fields
     *
     * @return self
     */
    public function setFields($fields)
    {
        $this->container['fields'] = $fields;

        return $this;
    }

    /**
     * Gets pricing
     *
     * @return \PandaDoc\Client\Model\PricingTablesResponse|null
     */
    public function getPricing()
    {
        return $this->container['pricing'];
    }

    /**
     * Sets pricing
     *
     * @param \PandaDoc\Client\Model\PricingTablesResponse|null $pricing pricing
     *
     * @return self
     */
    public function setPricing($pricing)
    {
        $this->container['pricing'] = $pricing;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string|null $version version
     *
     * @return self
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets sentBy
     *
     * @return mixed|null
     */
    public function getSentBy()
    {
        return $this->container['sentBy'];
    }

    /**
     * Sets sentBy
     *
     * @param mixed|null $sentBy sentBy
     *
     * @return self
     */
    public function setSentBy($sentBy)
    {
        $this->container['sentBy'] = $sentBy;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return \PandaDoc\Client\Model\DocumentDetailsResponseRecipients[]|null
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \PandaDoc\Client\Model\DocumentDetailsResponseRecipients[]|null $recipients recipients
     *
     * @return self
     */
    public function setRecipients($recipients)
    {
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets grandTotal
     *
     * @return \PandaDoc\Client\Model\DocumentDetailsResponseGrandTotal|null
     */
    public function getGrandTotal()
    {
        return $this->container['grandTotal'];
    }

    /**
     * Sets grandTotal
     *
     * @param \PandaDoc\Client\Model\DocumentDetailsResponseGrandTotal|null $grandTotal grandTotal
     *
     * @return self
     */
    public function setGrandTotal($grandTotal)
    {
        $this->container['grandTotal'] = $grandTotal;

        return $this;
    }

    /**
     * Gets linkedObjects
     *
     * @return \PandaDoc\Client\Model\DocumentDetailsResponseLinkedObjects[]|null
     */
    public function getLinkedObjects()
    {
        return $this->container['linkedObjects'];
    }

    /**
     * Sets linkedObjects
     *
     * @param \PandaDoc\Client\Model\DocumentDetailsResponseLinkedObjects[]|null $linkedObjects linkedObjects
     *
     * @return self
     */
    public function setLinkedObjects($linkedObjects)
    {
        $this->container['linkedObjects'] = $linkedObjects;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


