<?php
/**
 * QuoteResponseSectionItem
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PandaDoc Public API
 *
 * PandaDoc Public API documentation
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PandaDoc\Client\Model;

use \ArrayAccess;
use \PandaDoc\Client\ObjectSerializer;

/**
 * QuoteResponseSectionItem Class Doc Comment
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class QuoteResponseSectionItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'QuoteResponseSectionItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'sku' => 'string',
        'name' => 'string',
        'description' => 'string',
        'qty' => 'string',
        'price' => 'string',
        'cost' => 'string',
        'billingFrequency' => 'string',
        'contractTerm' => 'string',
        'pricingMethod' => 'string',
        'type' => 'string',
        'referenceType' => 'string',
        'options' => '\PandaDoc\Client\Model\QuoteResponseOptions',
        'customColumns' => 'array<string,string>',
        'discounts' => 'array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>',
        'taxes' => 'array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>',
        'fees' => 'array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>',
        'multipliers' => 'array<string,string>',
        'total' => 'string',
        'overallTotal' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'sku' => null,
        'name' => null,
        'description' => null,
        'qty' => null,
        'price' => null,
        'cost' => null,
        'billingFrequency' => null,
        'contractTerm' => null,
        'pricingMethod' => null,
        'type' => null,
        'referenceType' => null,
        'options' => null,
        'customColumns' => null,
        'discounts' => null,
        'taxes' => null,
        'fees' => null,
        'multipliers' => null,
        'total' => null,
        'overallTotal' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    #[\ReturnTypeWillChange]
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    #[\ReturnTypeWillChange]
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'sku' => 'sku',
        'name' => 'name',
        'description' => 'description',
        'qty' => 'qty',
        'price' => 'price',
        'cost' => 'cost',
        'billingFrequency' => 'billing_frequency',
        'contractTerm' => 'contract_term',
        'pricingMethod' => 'pricing_method',
        'type' => 'type',
        'referenceType' => 'reference_type',
        'options' => 'options',
        'customColumns' => 'custom_columns',
        'discounts' => 'discounts',
        'taxes' => 'taxes',
        'fees' => 'fees',
        'multipliers' => 'multipliers',
        'total' => 'total',
        'overallTotal' => 'overall_total'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'sku' => 'setSku',
        'name' => 'setName',
        'description' => 'setDescription',
        'qty' => 'setQty',
        'price' => 'setPrice',
        'cost' => 'setCost',
        'billingFrequency' => 'setBillingFrequency',
        'contractTerm' => 'setContractTerm',
        'pricingMethod' => 'setPricingMethod',
        'type' => 'setType',
        'referenceType' => 'setReferenceType',
        'options' => 'setOptions',
        'customColumns' => 'setCustomColumns',
        'discounts' => 'setDiscounts',
        'taxes' => 'setTaxes',
        'fees' => 'setFees',
        'multipliers' => 'setMultipliers',
        'total' => 'setTotal',
        'overallTotal' => 'setOverallTotal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'sku' => 'getSku',
        'name' => 'getName',
        'description' => 'getDescription',
        'qty' => 'getQty',
        'price' => 'getPrice',
        'cost' => 'getCost',
        'billingFrequency' => 'getBillingFrequency',
        'contractTerm' => 'getContractTerm',
        'pricingMethod' => 'getPricingMethod',
        'type' => 'getType',
        'referenceType' => 'getReferenceType',
        'options' => 'getOptions',
        'customColumns' => 'getCustomColumns',
        'discounts' => 'getDiscounts',
        'taxes' => 'getTaxes',
        'fees' => 'getFees',
        'multipliers' => 'getMultipliers',
        'total' => 'getTotal',
        'overallTotal' => 'getOverallTotal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    #[\ReturnTypeWillChange]
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    #[\ReturnTypeWillChange]
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    #[\ReturnTypeWillChange]
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    #[\ReturnTypeWillChange]
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['sku'] = $data['sku'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['qty'] = $data['qty'] ?? null;
        $this->container['price'] = $data['price'] ?? null;
        $this->container['cost'] = $data['cost'] ?? null;
        $this->container['billingFrequency'] = $data['billingFrequency'] ?? null;
        $this->container['contractTerm'] = $data['contractTerm'] ?? null;
        $this->container['pricingMethod'] = $data['pricingMethod'] ?? null;
        $this->container['type'] = $data['type'] ?? null;
        $this->container['referenceType'] = $data['referenceType'] ?? null;
        $this->container['options'] = $data['options'] ?? null;
        $this->container['customColumns'] = $data['customColumns'] ?? null;
        $this->container['discounts'] = $data['discounts'] ?? null;
        $this->container['taxes'] = $data['taxes'] ?? null;
        $this->container['fees'] = $data['fees'] ?? null;
        $this->container['multipliers'] = $data['multipliers'] ?? null;
        $this->container['total'] = $data['total'] ?? null;
        $this->container['overallTotal'] = $data['overallTotal'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    #[\ReturnTypeWillChange]
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    #[\ReturnTypeWillChange]
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string|null $sku sku
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setSku($sku)
    {
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets qty
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getQty()
    {
        return $this->container['qty'];
    }

    /**
     * Sets qty
     *
     * @param string|null $qty qty
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setQty($qty)
    {
        $this->container['qty'] = $qty;

        return $this;
    }

    /**
     * Gets price
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param string|null $price price
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param string|null $cost cost
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setCost($cost)
    {
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets billingFrequency
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getBillingFrequency()
    {
        return $this->container['billingFrequency'];
    }

    /**
     * Sets billingFrequency
     *
     * @param string|null $billingFrequency billingFrequency
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setBillingFrequency($billingFrequency)
    {
        $this->container['billingFrequency'] = $billingFrequency;

        return $this;
    }

    /**
     * Gets contractTerm
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getContractTerm()
    {
        return $this->container['contractTerm'];
    }

    /**
     * Sets contractTerm
     *
     * @param string|null $contractTerm contractTerm
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setContractTerm($contractTerm)
    {
        $this->container['contractTerm'] = $contractTerm;

        return $this;
    }

    /**
     * Gets pricingMethod
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getPricingMethod()
    {
        return $this->container['pricingMethod'];
    }

    /**
     * Sets pricingMethod
     *
     * @param string|null $pricingMethod pricingMethod
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setPricingMethod($pricingMethod)
    {
        $this->container['pricingMethod'] = $pricingMethod;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets referenceType
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getReferenceType()
    {
        return $this->container['referenceType'];
    }

    /**
     * Sets referenceType
     *
     * @param string|null $referenceType referenceType
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setReferenceType($referenceType)
    {
        $this->container['referenceType'] = $referenceType;

        return $this;
    }

    /**
     * Gets options
     *
     * @return \PandaDoc\Client\Model\QuoteResponseOptions|null
     */
    #[\ReturnTypeWillChange]
    public function getOptions()
    {
        return $this->container['options'];
    }

    /**
     * Sets options
     *
     * @param \PandaDoc\Client\Model\QuoteResponseOptions|null $options options
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setOptions($options)
    {
        $this->container['options'] = $options;

        return $this;
    }

    /**
     * Gets customColumns
     *
     * @return array<string,string>|null
     */
    #[\ReturnTypeWillChange]
    public function getCustomColumns()
    {
        return $this->container['customColumns'];
    }

    /**
     * Sets customColumns
     *
     * @param array<string,string>|null $customColumns customColumns
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setCustomColumns($customColumns)
    {
        $this->container['customColumns'] = $customColumns;

        return $this;
    }

    /**
     * Gets discounts
     *
     * @return array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>|null
     */
    #[\ReturnTypeWillChange]
    public function getDiscounts()
    {
        return $this->container['discounts'];
    }

    /**
     * Sets discounts
     *
     * @param array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>|null $discounts discounts
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setDiscounts($discounts)
    {
        $this->container['discounts'] = $discounts;

        return $this;
    }

    /**
     * Gets taxes
     *
     * @return array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>|null
     */
    #[\ReturnTypeWillChange]
    public function getTaxes()
    {
        return $this->container['taxes'];
    }

    /**
     * Sets taxes
     *
     * @param array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>|null $taxes taxes
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setTaxes($taxes)
    {
        $this->container['taxes'] = $taxes;

        return $this;
    }

    /**
     * Gets fees
     *
     * @return array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>|null
     */
    #[\ReturnTypeWillChange]
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     *
     * @param array<string,\PandaDoc\Client\Model\QuoteResponseSummaryDiscounts>|null $fees fees
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setFees($fees)
    {
        $this->container['fees'] = $fees;

        return $this;
    }

    /**
     * Gets multipliers
     *
     * @return array<string,string>|null
     */
    #[\ReturnTypeWillChange]
    public function getMultipliers()
    {
        return $this->container['multipliers'];
    }

    /**
     * Sets multipliers
     *
     * @param array<string,string>|null $multipliers multipliers
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setMultipliers($multipliers)
    {
        $this->container['multipliers'] = $multipliers;

        return $this;
    }

    /**
     * Gets total
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param string|null $total total
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setTotal($total)
    {
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets overallTotal
     *
     * @return string|null
     */
    #[\ReturnTypeWillChange]
    public function getOverallTotal()
    {
        return $this->container['overallTotal'];
    }

    /**
     * Sets overallTotal
     *
     * @param string|null $overallTotal overallTotal
     *
     * @return self
     */
    #[\ReturnTypeWillChange]
    public function setOverallTotal($overallTotal)
    {
        $this->container['overallTotal'] = $overallTotal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    #[\ReturnTypeWillChange]
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    #[\ReturnTypeWillChange]
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


