<?php
/**
 * UploadSectionStatusEnum
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PandaDoc Public API
 *
 * PandaDoc Public API documentation
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PandaDoc\Client\Model;
use \PandaDoc\Client\ObjectSerializer;

/**
 * UploadSectionStatusEnum Class Doc Comment
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UploadSectionStatusEnum
{
    /**
     * Possible values of this enum
     */
    const UPLOADED = 'document_sections_upload.UPLOADED';

    const PROCESSED = 'document_sections_upload.PROCESSED';

    const ERROR = 'document_sections_upload.ERROR';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    #[\ReturnTypeWillChange]
    public static function getAllowableEnumValues()
    {
        return [
            self::UPLOADED,
            self::PROCESSED,
            self::ERROR
        ];
    }
}


