<?php
/**
 * WebhookSubscriptionStatusEnum
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PandaDoc Public API
 *
 * PandaDoc Public API documentation
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PandaDoc\Client\Model;
use \PandaDoc\Client\ObjectSerializer;

/**
 * WebhookSubscriptionStatusEnum Class Doc Comment
 *
 * @category Class
 * @package  PandaDoc\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookSubscriptionStatusEnum
{
    /**
     * Possible values of this enum
     */
    const ACTIVE = 'ACTIVE';

    const INACTIVE = 'INACTIVE';

    const DEACTIVATED = 'DEACTIVATED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::INACTIVE,
            self::DEACTIVATED
        ];
    }
}


